/** @deprecated Import from @/lib/api/atendimento.functions */
export {
  connectAtendimentoEvolutionServer,
  createWabaAutomationServer,
  deleteWabaAutomationServer,
  deleteWabaContactServer,
  disconnectAtendimentoEvolutionServer,
  fetchAtendimentoConfigServer,
  fetchAtendimentoConversationsServer,
  fetchAtendimentoMessagesServer,
  fetchWabaAutomationServer,
  fetchWabaAutomationsServer,
  fetchWabaCoexistenceStatusServer,
  fetchWabaConfigServer,
  fetchWabaContactsServer,
  fetchWabaConversationsServer,
  fetchWabaMessagesServer,
  fetchWabaTemplatesServer,
  markAtendimentoConversationReadServer,
  markWabaConversationReadServer,
  saveAtendimentoMetaConfigServer,
  saveWabaConfigServer,
  sendAtendimentoMessageServer,
  sendWabaMessageServer,
  setAtendimentoProviderServer,
  setWabaAutomationActiveServer,
  triggerWabaCoexistenceSyncServer,
  updateWabaAutomationServer,
  upsertWabaContactServer,
} from "@/lib/api/atendimento.functions";
