// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

type SupabaseClient = ReturnType<typeof createClient<Database>>;

export function isSupabaseConfigured() {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;
  return Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
}

function createNoopQueryBuilder<T = unknown>(data: T = [] as T) {
  const response = { data, error: null as const };
  const builder = {
    select: () => builder,
    insert: () => builder,
    update: () => builder,
    upsert: () => builder,
    delete: () => builder,
    eq: () => builder,
    neq: () => builder,
    in: () => builder,
    ilike: () => builder,
    lt: () => builder,
    not: () => builder,
    order: () => builder,
    limit: () => builder,
    maybeSingle: async () => ({ data: null, error: null }),
    single: async () => ({ data: null, error: null }),
    then: (
      onfulfilled?: ((value: typeof response) => unknown) | null,
      onrejected?: ((reason: unknown) => unknown) | null,
    ) => Promise.resolve(response).then(onfulfilled, onrejected),
    catch: (onrejected?: ((reason: unknown) => unknown) | null) =>
      Promise.resolve(response).catch(onrejected),
    finally: (onfinally?: (() => void) | null) => Promise.resolve(response).finally(onfinally),
  };
  return builder;
}

function createNoopSupabaseClient(): SupabaseClient {
  const demoAuthError = {
    message: "Supabase nao configurado. Use o painel demo em /t/norfood/dashboard ou configure o .env.",
    name: "AuthDemoModeError",
    status: 400,
  };

  const noopChannel = {
    on: () => noopChannel,
    subscribe: () => noopChannel,
    unsubscribe: () => undefined,
  };

  return {
    auth: {
      getSession: async () => ({ data: { session: null }, error: null }),
      getUser: async () => ({ data: { user: null }, error: null }),
      getClaims: async () => ({ data: null, error: null }),
      signInWithPassword: async () => ({
        data: { user: null, session: null },
        error: demoAuthError,
      }),
      signUp: async () => ({
        data: { user: null, session: null },
        error: demoAuthError,
      }),
      signOut: async () => ({ error: null }),
      resetPasswordForEmail: async () => ({ data: {}, error: demoAuthError }),
      updateUser: async () => ({ data: { user: null }, error: demoAuthError }),
      verifyOtp: async () => ({ data: { user: null, session: null }, error: demoAuthError }),
      onAuthStateChange: () => ({
        data: { subscription: { unsubscribe: () => undefined } },
      }),
    },
    from: () => createNoopQueryBuilder(),
    rpc: async () => ({ data: null, error: demoAuthError }),
    channel: () => noopChannel,
    removeChannel: () => undefined,
  } as unknown as SupabaseClient;
}

function createSupabaseClient() {
  if (!isSupabaseConfigured()) {
    console.warn(
      "[Supabase] Credenciais ausentes — modo demo local ativo. Configure VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY no .env para usar o banco real.",
    );
    return createNoopSupabaseClient();
  }

  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  return createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  });
}

let _supabase: SupabaseClient | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as SupabaseClient, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
