// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { isSupabaseConfigured } from "./client";

type SupabaseAdminClient = ReturnType<typeof createClient<Database>>;

function createNoopQueryBuilder<T = unknown>(data: T = [] as T) {
  const response = { data, error: null as const };
  const builder = {
    select: () => builder,
    insert: () => builder,
    update: () => builder,
    upsert: () => builder,
    delete: () => builder,
    eq: () => builder,
    neq: () => builder,
    in: () => builder,
    ilike: () => builder,
    lt: () => builder,
    not: () => builder,
    order: () => builder,
    limit: () => builder,
    maybeSingle: async () => ({ data: null, error: null }),
    single: async () => ({ data: null, error: null }),
    then: (
      onfulfilled?: ((value: typeof response) => unknown) | null,
      onrejected?: ((reason: unknown) => unknown) | null,
    ) => Promise.resolve(response).then(onfulfilled, onrejected),
    catch: (onrejected?: ((reason: unknown) => unknown) | null) =>
      Promise.resolve(response).catch(onrejected),
    finally: (onfinally?: (() => void) | null) => Promise.resolve(response).finally(onfinally),
  };
  return builder;
}

function createNoopSupabaseAdminClient(): SupabaseAdminClient {
  return {
    auth: {
      admin: {
        createUser: async () => ({ data: { user: null }, error: null }),
        updateUserById: async () => ({ data: { user: null }, error: null }),
        listUsers: async () => ({ data: { users: [] }, error: null }),
      },
    },
    from: () => createNoopQueryBuilder(),
    rpc: async () => ({ data: null, error: null }),
  } as unknown as SupabaseAdminClient;
}

function createSupabaseAdminClient() {
  if (!isSupabaseConfigured()) {
    console.warn(
      "[Supabase] Service role ausente — modo demo local no servidor. Configure SUPABASE_URL e SUPABASE_SERVICE_ROLE_KEY no .env.",
    );
    return createNoopSupabaseAdminClient();
  }

  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  return createClient<Database>(SUPABASE_URL!, SUPABASE_SERVICE_ROLE_KEY!, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: SupabaseAdminClient | undefined;

export const supabaseAdmin = new Proxy({} as SupabaseAdminClient, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
